Version : 0.2 
phases :
  install:  
      commands:
        - echo Installing NGINX
        - apt-get install sudo -y
        - sudo apt-get update
        - sudo apt-get install nginx -y
  
  build:
      commands:
        - echo Building
        - cp -r Folder1/* /var/www/html
        - 

  post_build:
      commands: 
        - echo configuring linux 

artifacts:
  files:
    - Folder1/*
    - Folder1/scripts/*
    - Folder1/bootstrapewbsite/*
    - Folder1/bootstrapwebsite/css/*
    - Folder1/bootstrapwebsite/js/*
    - Folder1/PHP/*
    - buildspec.yml
    - appspec.yml
